design change: drop lalrpop
Ok, I'm finding that its becoming harder to represent the grammar that I'm
wanting in lalrpop.  lalrpop's design as a metalanguage to create other
languages while being written in itself makes it fairly hard to understand.

So I'm dropping it in favor of... unknown.

```
error: failed to run custom build command for `sevenfold v0.1.0 (/Users/sjanes/contexts/mtp0/from-thenceforth/sevenfold)`

Caused by:
  process didn't exit successfully: `/Users/sjanes/contexts/mtp0/from-thenceforth/sevenfold/target/debug/build/sevenfold-ef8d6d13c98840ed/build-script-build` (exit status: 1)
  --- stdout
  processing file `./src/r7rs.lalrpop`
  ./src/r7rs.lalrpop:75:5: 75:22 error: invalid regular expression: regex parse error:
      .*(?!(#\||\|#))
        ^^^
  error: look-around, including look-ahead and look-behind, is not supported

  --- stderr
        r".*(?!(#\||\|#))",
        ~~~~~~~~~~~~~~~~~~
```